Repository codestates-seb/seb41_main_018, pull requests merged in 2023-01, with the labels that each got.

#4 feat: entity 구현
  server/src/main/java/com/seb41_main_018/mainproject/comment/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/home/HomeController.java
  server/src/main/java/com/seb41_main_018/mainproject/user/User.java
Labels: feat

#10 Feat: Utils#2
  server/src/main/java/com/seb41_main_018/mainproject/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/seb41_main_018/mainproject/audit/Auditable.java
  server/src/main/java/com/seb41_main_018/mainproject/exception/BusinessLogicException.java
  server/src/main/java/com/seb41_main_018/mainproject/exception/ExceptionCode.java
  server/src/main/java/com/seb41_main_018/mainproject/utils/CustomBeanUtils.java
  server/src/main/java/com/seb41_main_018/mainproject/utils/UriCreator.java
Labels: feat

#14 Feat entity #1
  server/src/main/java/com/seb41_main_018/mainproject/post/Post.java
Labels: feat

#18 BE: Feat comment 엔티티 추가
  server/src/main/java/com/seb41_main_018/mainproject/comment/entity/Comment.java
Labels: feat

#21 BE: Feat Category 엔티티 추가
  server/src/main/java/com/seb41_main_018/mainproject/category/entity/Category.java
Labels: feat

#22 Feat Route , Like entity_구현 #3
  server/src/main/java/com/seb41_main_018/mainproject/like/Like.java
  server/src/main/java/com/seb41_main_018/mainproject/route/entity/Route.java
Labels: feat

#25 BE: feat entity #1
  server/src/main/java/com/seb41_main_018/mainproject/post/entity/Post.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/entity/Tag.java
Labels: feat

#29 BE: Refactor (comment, category) entity, controller 수정
  server/src/main/java/com/seb41_main_018/mainproject/category/entity/Category.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/controller/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/entity/Comment.java
Labels: feat

#30 Feat User, Like, Route controller #3
  server/src/main/java/com/seb41_main_018/mainproject/like/controller/LikeController.java
  server/src/main/java/com/seb41_main_018/mainproject/route/controller/RouteController.java
  server/src/main/java/com/seb41_main_018/mainproject/user/controller/UserController.java
Labels: feat

#31 BE: Feat comment, category Dto 추가
  server/src/main/java/com/seb41_main_018/mainproject/category/dto/CategoryDto.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
Labels: feat

#33 BE: feat controller #1
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
  server/src/main/java/com/seb41_main_018/mainproject/content/entity/Content.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/controller/TagController.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/entity/Tag.java
Labels: feat

#37 Refactor Like, User, Route entity #3
  server/src/main/java/com/seb41_main_018/mainproject/like/entity/Like.java
  server/src/main/java/com/seb41_main_018/mainproject/route/entity/Route.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
Labels: refactor

#38 BE: Refactor comment dto 수정
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
Labels: refactor

#41 Feat DTO #1
  server/src/main/java/com/seb41_main_018/mainproject/content/dto/ContentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/content/entity/Content.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/dto/TagDto.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/entity/Tag.java
Labels: feat

#42 BE: Refactor Comment, Category Entity
  server/src/main/java/com/seb41_main_018/mainproject/category/controller/CategoryController.java
  server/src/main/java/com/seb41_main_018/mainproject/category/mapper/CatrgoryMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/controller/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/entity/Comment.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/mapper/CommentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
Labels: refactor

#43 BE : Feat user #3
  server/src/main/java/com/seb41_main_018/mainproject/user/controller/UserController.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserAllResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPatchDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPostDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
  server/src/main/java/com/seb41_main_018/mainproject/user/mapper/UserMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/user/repository/UserRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/user/service/UserService.java
Labels: feat

#47 BE: Feat (Comment, Category) Repository, Service
  server/src/main/java/com/seb41_main_018/mainproject/category/repository/CategoryRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/category/service/CategoryService.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/entity/Comment.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/repository/CommentRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/service/CommentService.java
Labels: feat

#48 Feat mapper, repository #1
  server/src/main/java/com/seb41_main_018/mainproject/content/mapper/ContentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/content/repository/ContentRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/content/service/ContentService.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/mapper/TagMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/repository/TagRepository.java
Labels: feat

#50 BE: Refactor Comment, Category Service
  server/src/main/java/com/seb41_main_018/mainproject/category/controller/CategoryController.java
  server/src/main/java/com/seb41_main_018/mainproject/category/service/CategoryService.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/mapper/CommentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/service/CommentService.java
Labels: refactor

#53 BE: Feat Comment, Category Controller
  server/src/main/java/com/seb41_main_018/mainproject/category/controller/CategoryController.java
  server/src/main/java/com/seb41_main_018/mainproject/category/mapper/CategoryMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/category/service/CategoryService.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/controller/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/mapper/CommentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/service/CommentService.java
Labels: feat

#54 BE: Refactor CategoryController
  server/src/main/java/com/seb41_main_018/mainproject/category/controller/CategoryController.java
Labels: refactor

#56 BE: Feat controller #1
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
  server/src/main/java/com/seb41_main_018/mainproject/content/repository/ContentRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/content/service/ContentService.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/controller/TagController.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/service/TagService.java
Labels: feat

#61 Feat like #3
  server/src/main/java/com/seb41_main_018/mainproject/heart/controller/HeartController.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/dto/HeartDto.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/entity/Heart.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/repository/HeartRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/service/HeartService.java
  server/src/main/java/com/seb41_main_018/mainproject/like/controller/LikeController.java
Labels: feat

#62 refactor : UserService#3
  server/src/main/java/com/seb41_main_018/mainproject/user/service/UserService.java
Labels: refactor

#64 Feat route #1
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
  server/src/main/java/com/seb41_main_018/mainproject/route/controller/RouteController.java
  server/src/main/java/com/seb41_main_018/mainproject/route/dto/RouteDto.java
  server/src/main/java/com/seb41_main_018/mainproject/route/entity/Route.java
  server/src/main/java/com/seb41_main_018/mainproject/route/mapper/RouteMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/route/repository/RouteRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/route/service/RouteService.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/controller/TagController.java
Labels: feat

#72 BE: Fix User Domain 디버깅
  .idea/jarRepositories.xml
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPatchDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPostDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
  server/src/main/resources/application.yml
Labels: bug

#75 BE: Fix User Domain 디버깅
  .idea/jarRepositories.xml
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPatchDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPostDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
  server/src/main/resources/application.yml
Labels: bug

#77 Debug : user entity
  server/src/main/java/com/seb41_main_018/mainproject/comment/entity/Comment.java
  server/src/main/java/com/seb41_main_018/mainproject/content/dto/ContentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/content/mapper/ContentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
Labels: bug

#78 debug: Comment - entity / controller / service
  server/src/main/java/com/seb41_main_018/mainproject/comment/controller/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/entity/Comment.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/service/CommentService.java
Labels: bug

#79 Feat: loginpage, signup 1차 구현
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Button.js
  client/src/components/SocialButton.js
  client/src/index.css
  client/src/pages/Login.js
  client/src/pages/SignUp.js
Labels: feat

#88 BE: Feat Test Case sample
  server/src/main/java/com/seb41_main_018/mainproject/comment/entity/Comment.java
  server/src/main/java/com/seb41_main_018/mainproject/route/entity/Route.java
  server/src/test/java/com/seb41_main_018/mainproject/comment/controller/CommentControllerTest.java
  server/src/test/java/com/seb41_main_018/mainproject/content/ContentServiceTest.java
  server/src/test/java/com/seb41_main_018/mainproject/content/controller/ContentControllerTest.java
  server/src/test/java/com/seb41_main_018/mainproject/route/controller/RouteControllerTest.java
  server/src/test/java/com/seb41_main_018/mainproject/routeplace/controller/RoutePlaceControllerTest.java
  server/src/test/java/com/seb41_main_018/mainproject/tag/controller/TagControllerTest.java
Labels: refactor

#89 Debug : test service #3
  server/src/test/java/com/seb41_main_018/mainproject/user/service/UserServiceTest.java
Labels: bug

#90 Feat/fe loginpage, signuppage
  client/package.json
  client/src/App.js
  client/src/index.js
  client/src/pages/Login,SignUp page/Login.js
  client/src/pages/Login,SignUp page/SignUp.js
  client/src/pages/Login,SignUp page/loginstyle.js
  client/src/pages/Login.js
  client/src/pages/SignUp.js
Labels: feat

#98 refactor : heart
  server/src/main/java/com/seb41_main_018/mainproject/constant/HeartType.java
  server/src/main/java/com/seb41_main_018/mainproject/constant/ThemeType.java
  server/src/main/java/com/seb41_main_018/mainproject/content/dto/ContentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/content/entity/Content.java
  server/src/main/java/com/seb41_main_018/mainproject/content/mapper/ContentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/content/service/ContentService.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/controller/HeartController.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/dto/HeartDto.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/entity/Heart.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/mapper/HeartMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/repository/HeartRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/service/HeartService.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserAllResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPatchDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPostDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
  server/src/main/java/com/seb41_main_018/mainproject/user/service/UserService.java
  server/src/test/java/com/seb41_main_018/mainproject/category/service/CategoryServiceTest.java
  server/src/test/java/com/seb41_main_018/mainproject/comment/service/CommentServiceTest.java
  server/src/test/java/com/seb41_main_018/mainproject/content/service/ContentServiceTest.java
  server/src/test/java/com/seb41_main_018/mainproject/route/service/RouteServiceTest.java
  server/src/test/java/com/seb41_main_018/mainproject/routeplace/service/RoutePlaceServiceTest.java
  server/src/test/java/com/seb41_main_018/mainproject/tag/service/TagServiceTest.java
Labels: bug

#105 Feat security#3
  server/build.gradle
  server/src/main/java/com/seb41_main_018/mainproject/auth/dto/LoginDto.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/handler/SuccessUserInfo.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/handler/UserAccessDeniedHandler.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/utils/ErrorResponder.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/utils/MemberDetailsService.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/utils/UserRegistrationApplicationEvent.java
  server/src/main/java/com/seb41_main_018/mainproject/config/SecurityConfiguration.java
  server/src/main/java/com/seb41_main_018/mainproject/user/controller/UserController.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
  server/src/main/java/com/seb41_main_018/mainproject/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: feat

#108 FE: login/signup 화면 정렬
  client/src/pages/Login,SignUp page/Login.js
  client/src/pages/Login,SignUp page/loginstyle.js
  client/src/pages/Login.js
Labels: css

#109 Be : feat jwt
  server/src/main/java/com/seb41_main_018/mainproject/comment/controller/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/service/CommentService.java
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
  server/src/main/java/com/seb41_main_018/mainproject/content/dto/ContentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/content/service/ContentService.java
  server/src/main/java/com/seb41_main_018/mainproject/exception/ExceptionCode.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPatchDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/service/UserService.java
Labels: refactor

#116 BE : Refactor, Category
  server/src/main/java/com/seb41_main_018/mainproject/category/entity/Category.java
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
  server/src/main/java/com/seb41_main_018/mainproject/content/dto/ContentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/content/entity/Content.java
  server/src/main/java/com/seb41_main_018/mainproject/content/mapper/ContentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/content/repository/ContentRepository.java
Labels: refactor

#117 BE: 전체조회 기능 추가
  server/src/main/java/com/seb41_main_018/mainproject/comment/controller/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
  server/src/main/java/com/seb41_main_018/mainproject/route/controller/RouteController.java
  server/src/main/java/com/seb41_main_018/mainproject/routeplace/controller/RoutePlaceController.java
  server/src/main/java/com/seb41_main_018/mainproject/routeplace/service/RoutePlaceService.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/controller/TagController.java
Labels: feat

#127 FE : Detail page
  client/src/assets/sampleImg/sam1_1.png
  client/src/assets/sampleImg/sam1_2.jpeg
  client/src/assets/sampleImg/sam1_3.jpg
  client/src/assets/sampleImg/sam2.jpg
  client/src/assets/sampleImg/sam3_1.jpeg
  client/src/assets/sampleImg/sam3_2.jpeg
  client/src/assets/sampleImg/white.png
  client/src/components/Detail_Img.js
  client/src/components/Detailform.js
  client/src/components/DetailformItems.js
  client/src/index.js
  client/src/pages/Detail.js
  client/src/state/atom.js
Labels: feat

#136 BE: MySQL 및 서비스 구현
  server/build.gradle
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/mapper/CommentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/service/CommentService.java
  server/src/main/java/com/seb41_main_018/mainproject/content/entity/Content.java
  server/src/main/java/com/seb41_main_018/mainproject/content/service/ContentService.java
  server/src/main/resources/application-server.yml
Labels: feat

#137 FE : detail img 개별 출력
  client/src/components/Detail_Img.js
Labels: feat

#141 Fe: Image Upload
  client/src/components/ImgUpload.js
  client/src/components/PostformItems.js
  client/src/state/atom.js
Labels: feat

#143 Feat: map 구현중 중간 업로드
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/pages/PostPage/Post.js
  client/src/pages/PostPage/searchMap.js
  client/src/pages/PostPage/testsearchMap.js
Labels: feat

#151 BE: S3 Image 업로드 기능구현
  server/build.gradle
  server/src/main/java/com/seb41_main_018/mainproject/config/S3Config.java
  server/src/main/java/com/seb41_main_018/mainproject/config/S3Uploader.java
  server/src/main/java/com/seb41_main_018/mainproject/image/ImageController.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
Labels: feat

#152 BE : refactor userInfo
  server/src/main/java/com/seb41_main_018/mainproject/auth/handler/SuccessUserInfo.java
  server/src/main/java/com/seb41_main_018/mainproject/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/comment/repository/CommentRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/content/dto/ContentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/content/repository/ContentRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/dto/HeartDto.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/repository/HeartRepository.java
  server/src/main/java/com/seb41_main_018/mainproject/user/controller/UserController.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserAllResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPatchDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPostDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
  server/src/main/java/com/seb41_main_018/mainproject/user/mapper/UserMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/user/service/UserService.java
Labels: refactor

#155 BE: Refactor Swagger 수정
  server/src/main/java/com/seb41_main_018/mainproject/comment/controller/CommentController.java
  server/src/main/java/com/seb41_main_018/mainproject/content/controller/ContentController.java
  server/src/main/java/com/seb41_main_018/mainproject/heart/controller/HeartController.java
  server/src/main/java/com/seb41_main_018/mainproject/route/controller/RouteController.java
  server/src/main/java/com/seb41_main_018/mainproject/tag/controller/TagController.java
  server/src/main/java/com/seb41_main_018/mainproject/user/controller/UserController.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application.yml
  server/src/main/resources/application2.yml
Labels: refactor

#165 지도 기능 1차구현 merge를 위한 커밋
  client/src/components/TitleCard.js
  client/src/pages/Post.js
  client/src/pages/PostPage/DetailMap.js
  client/src/pages/PostPage/NewPost.js
  client/src/pages/PostPage/PostMap/PostMap.js
  client/src/pages/PostPage/PostMap/PostMapFive.js
  client/src/pages/PostPage/PostMap/PostMapFour.js
  client/src/pages/PostPage/PostMap/PostMapThree.js
  client/src/pages/PostPage/PostMap/PostMapTwo.js
  client/src/state/atom.js
Labels: feat

#169 FE: home get 요청
  client/src/App.css
  client/src/App.js
  client/src/components/Home_components/HomeItems.js
  client/src/components/TitleCard.js
  client/src/pages/Detail.js
  client/src/pages/Home.js
  client/src/pages/Post.js
  client/src/pages/PostPage/Post.js
  client/src/state/atom.js
  client/src/util/UseForm.js
  client/src/util/axiosDetail.js
Labels: feat

#171 FE: user info get 요청
  client/src/pages/Login,SignUp page/Login.js
  client/src/state/atom.js
  client/src/util/axiosUser.js
Labels: feat

#176 FE: Mypage 서버 연결
  client/src/components/Header.js
  client/src/components/Mypage_components/MyInfo.js
  client/src/components/Mypage_components/MyPost.js
  client/src/components/Mypage_components/MyPostItem.js
  client/src/components/Mypage_components/MyReview.js
  client/src/components/Mypage_components/UserDeleteModal.js
  client/src/pages/Login,SignUp page/Login.js
  client/src/pages/Mypage.js
  client/src/state/atom.js
  client/src/util/axiosUser.js
Labels: feat

#178 FE: comment 조회 / 등록
  client/src/components/Detail_components/ReviewItem.js
  client/src/components/Detail_components/Reviewform.js
  client/src/state/atom.js
  client/src/util/axiosDetail.js
Labels: feat

#182 FE: 추가 사항 업데이트
  client/package.json
  client/src/components/Detail_components/Reviewform.js
  client/src/pages/Detail.js
  client/src/pages/Home.js
  client/src/state/atom.js
  client/src/util/axiosDetail.js
Labels: feat

#183 FE: 카테고리 선택 검색 기능
  client/src/components/Categorybar.js
  client/src/pages/Result.js
  client/src/state/atom.js
  client/src/util/axiosDetail.js
Labels: feat

#187 FE: 검색 기능 구현
  README.md
  client/public/favicon.ico
  client/public/favicon.png
  client/public/index.html
  client/src/components/Categorybar.js
  client/src/components/Detail_components/Reviewform.js
  client/src/components/Header.js
  client/src/pages/Home.js
  client/src/pages/Login,SignUp page/Login.js
  client/src/pages/Mypage.js
  client/src/pages/Result.js
  client/src/state/atom.js
  client/src/util/axiosDetail.js
  package.json
Labels: feat

#188 BE : feat user image
  server/src/main/java/com/seb41_main_018/mainproject/comment/dto/CommentDto.java
  server/src/main/java/com/seb41_main_018/mainproject/config/MultipartJackson2HttpMessageConverter.java
  server/src/main/java/com/seb41_main_018/mainproject/config/S3Uploader.java
  server/src/main/java/com/seb41_main_018/mainproject/content/dto/ContentAllResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/content/mapper/ContentMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/user/controller/UserController.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserAllResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserPatchDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/dto/UserResponseDto.java
  server/src/main/java/com/seb41_main_018/mainproject/user/entity/User.java
  server/src/main/java/com/seb41_main_018/mainproject/user/mapper/UserMapper.java
  server/src/main/java/com/seb41_main_018/mainproject/user/service/UserService.java
Labels: feat

#190 post페이지 hookform 병합1차완료
  client/src/Common.js
  client/src/components/Post_components/ImgUpload.js
  client/src/components/Post_components/PostformItems.js
  client/src/components/Post_components/Tag.js
  client/src/pages/Post.js
  client/src/pages/PostPage/NewPost.js
  client/src/pages/PostPage/PostMap/PostMap.js
  client/src/pages/PostPage/PostMap/PostMapFive.js
  client/src/pages/PostPage/PostMap/PostMapFour.js
  client/src/pages/PostPage/PostMap/PostMapThree.js
  client/src/pages/PostPage/PostMap/PostMapTwo.js
  client/src/state/atom.js
Labels: feat

#192 Feat/fe result
  client/src/assets/categoryImg/가족여행.png
  client/src/components/Categorybar.js
  client/src/components/Detail_components/Detailform.js
  client/src/components/Mypage_components/MyInfo.js
  client/src/components/Mypage_components/MyLike.js
  client/src/components/Mypage_components/MyPostItem.js
  client/src/components/Mypage_components/MyReview.js
  client/src/components/Post_components/ImgUpload.js
  client/src/components/Post_components/Tag.js
  client/src/pages/Detail.js
  client/src/pages/Mypage.js
  client/src/pages/PostPage/NewPost.js
  client/src/pages/Result.js
  client/src/state/atom.js
  client/src/util/axiosContents.js
Labels: feat

#199 FE : content, comment 삭제
  client/src/components/Detail_components/Detailform.js
  client/src/components/Detail_components/ReviewItem.js
  client/src/components/Detail_components/Reviewform.js
  client/src/components/Home_components/HomeItems.js
  client/src/components/Mypage_components/MyLike.js
  client/src/pages/Detail.js
  client/src/pages/Login,SignUp page/Login.js
  client/src/pages/Login,SignUp page/SignUp.js
  client/src/state/atom.js
  client/src/util/axiosContents.js
Labels: feat

#201 FE: 수정사항 반영
  client/src/App.js
  client/src/components/Detail_components/ReviewItem.js
  client/src/components/Detail_components/Reviewform.js
  client/src/components/Post_components/ImgUpload.js
  client/src/pages/Detail.js
  client/src/pages/PostPage/NewPost.js
  client/src/pages/PostPage/Post.js
  client/src/util/axiosContents.js
  client/src/명세서.js
Labels: feat

#208 FE: error 수정
  client/package.json
  client/src/components/Detail_components/Detailform.js
  client/src/components/Detail_components/ReviewDeleteModal.js
  client/src/components/Detail_components/ReviewItem.js
  client/src/components/Detail_components/Reviewform.js
  client/src/components/Header.js
  client/src/components/Home_components/HomeItems.js
  client/src/components/Home_components/RegionItems.js
  client/src/components/Loding.js
  client/src/pages/Detail.js
  client/src/pages/Home.js
  client/src/pages/Login,SignUp page/Login.js
  client/src/pages/Mypage.js
  client/src/pages/Result.js
  client/src/state/atom.js
  client/src/util/axiosContents.js
Labels: bug, feat

#209 FE: 본인 작성 글에서만 수정/삭제 버튼 노출
  client/src/components/Categorybar.js
  client/src/pages/Detail.js
  client/src/pages/Result.js
Labels: feat

#223 detail사진 랜덤 표시 기능 구현 및 sampleimg 삭제 완료
  client/src/assets/image.js
  client/src/components/Detail_components/Detail_Img.js
  client/src/components/Home_components/HomeItems.js
Labels: feat

#224 Feat/fe change mypage image src
  client/src/assets/sampleImg/Img1.webp
  client/src/assets/sampleImg/Img10.jpeg
  client/src/assets/sampleImg/Img11.jpg
  client/src/assets/sampleImg/Img12.jpeg
  client/src/assets/sampleImg/Img13.webp
  client/src/assets/sampleImg/Img14.webp
  client/src/assets/sampleImg/Img15.webp
  client/src/assets/sampleImg/Img16.webp
  client/src/assets/sampleImg/Img17.webp
  client/src/assets/sampleImg/Img18.webp
  client/src/assets/sampleImg/Img19.webp
  client/src/assets/sampleImg/Img2.webp
  client/src/assets/sampleImg/Img20.webp
  client/src/assets/sampleImg/Img21.webp
  client/src/assets/sampleImg/Img3.webp
  client/src/assets/sampleImg/Img4.webp
  client/src/assets/sampleImg/Img5.png
  client/src/assets/sampleImg/Img6.jpeg
  client/src/assets/sampleImg/Img7.jpg
  client/src/assets/sampleImg/Img8.jpg
  client/src/assets/sampleImg/Img9.webp
  client/src/components/Mypage_components/MyLike.js
  client/src/components/Mypage_components/MyPostItem.js
  client/src/components/Mypage_components/MyReview.js
  client/src/pages/Mypage.js
Labels: feat
